name: 'medallion_architecture'
version: '1.0.0'
config-version: 2

profile: 'spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medallion_architecture:
    silver:
      +materialized: table
      +schema: silver
      +location_root: "hdfs://namenode:9000/user/events/silver"
    gold:
      +materialized: table
      +schema: gold
      +location_root: "hdfs://namenode:9000/user/events/gold"