global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'hadoop'
    static_configs:
      - targets: ['hadoop-exporter:9123']   # ✅ فقط از اینجا می‌تونه بخونه

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']    # ✅ کافکا فقط با Exporter

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:4040', 'spark-worker:4040']   # ✅ فقط اگر Spark به درستی پیکربندی شده باشه (بهتره JMX Exporter بذاری)

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
