spark:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-master
      port: 10000
      user: hadoop
      schema: default
      connect_timeout: 60
      connect_retries: 5
      connect_retry_delay: 5